name: test

on:
  push:
    branches: [ master ]
  pull_request:

jobs:
  local:
    name: local tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@master
      with:
        version: 10.x

    - run: yarn install
    - run: yarn build
    - run: yarn format-check
    - run: yarn test

    - uses: ./

    - if: matrix.os == 'windows-latest'
      run: 'Get-ChildItem env:'
    - if: matrix.os != 'windows-latest'
      run: env

    - run: metanorma help
  remote:
    name: remote tests
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ ubuntu-latest, windows-latest, macos-latest ]
    steps:
    - uses: actions-mn/setup@master
    - run: metanorma help
    
    

    - run: metanorma version
